version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app1
      - app2
      - app3
      - app4
    networks:
      - app-network

  app1:
    build: .
    environment:
      - PORT=8000
      - DB_URL=mongodb://mongo:27017/chat-APP
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  app2:
    build: .
    environment:
      - PORT=8001
      - DB_URL=mongodb://mongo:27017/chat-APP
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  app3:
    build: .
    environment:
      - PORT=8002
      - DB_URL=mongodb://mongo:27017/chat-APP
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  app4:
    build: .
    environment:
      - PORT=8003
      - DB_URL=mongodb://mongo:27017/chat-APP
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - app-network

  mongo:
    image: mongo:6
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=chat-APP
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge